# Generated by Django 5.2.5 on 2025-08-24 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_curso_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='api.estudiante'),
        ),
    ]
